# Generated by Django 2.0.7 on 2019-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
